#____________________________________________________________________________________________
# servoing
#____________________________________________________________________________________________
# --

float64[] rough_vertices
# rough_vertices : 보정전 8개 물체의 좌표 (8*3 = 24개)
---
float64[] correct_vertices
float64   fitness
# correct_vertices : 보정된 8개 물체의 좌표 (8*3 = 24개)
