#____________________________________________________________________________________________
# vision_vertices
#____________________________________________________________________________________________
# --

---
float64[] vertices
string[] names
# vertices : 비전에서 찾은 n개의 물체 8개의 좌표 (n*8*3 = 24n개)
# names : 찾은 n개의 물체의 이름
